services:

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    container_name: devbook_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devbook

volumes:
  database: